import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Drones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-50" >
      <link rel="icon" href="https://launion.com.gt/wp-content/uploads/2019/01/ICONO-100x100.png" sizes="32x32"></link>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full `}
         data-testim-main-word-scripts-loaded="true"
      >
        {children}
      </body>
    </html>
  );
}
