import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Drones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-white" >
      <link rel="icon" href="https://reclutamiento.launion.com.gt/favicon.ico"></link>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full `}
        data-testim-main-word-scripts-loaded="true"
      >
        {children}
      </body>
    </html>
  );
}
